version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: company_contracts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/company_contracts_db
    ports:
      - "8008:8008"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8008"]

volumes:
  postgres_data:
