version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_container
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8008:8008"
    command: ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8008"]

volumes:
  postgres_data:
