"""Update Contract model

Revision ID: d81312196e98
Revises: 4332f2d05a0d
Create Date: 2025-01-27 20:46:06.694321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd81312196e98'
down_revision: Union[str, None] = '4332f2d05a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'validity_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contracts', 'signing_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contracts', 'fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('contracts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contracts', 'fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('contracts', 'signing_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contracts', 'validity_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
